export const GET_All_BOOKS = "GET_All_BOOKS";
export const SORT_BOOKS_OF_CATEGORIES = "SORT_BOOKS_OF_CATEGORIES";
export const SEARCH_BOOK = "SEARCH_BOOK";
export const GET_MORE_BOOK = "GET_MORE_BOOK";
export const SORT_BOOKS_LIST= "SORT_BOOKS_LIST";
export const GET_ONE_BOOK= "GET_ONE_BOOK";